{{ if .Values.oidc.encodedClientID }}
---
apiVersion: dex.coreos.com/v1
kind: OAuth2Client
metadata:
  name: {{ .Values.oidc.encodedClientID }}
  namespace: {{ .Values.oidc.dexNamespace }}
id: {{ .Values.oidc.clientID }}
name: {{ .Values.oidc.clientID }}
public: false
redirectURIs:
  - https://{{ .Values.ingress.host }}/dg_callback
secret: {{ .Values.oidc.clientSecret }}

{{ end }}

