---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dexgate
  namespace: {{ .Release.Namespace  }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dexgate
  namespace: {{ .Release.Namespace  }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dexgate
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace  }}  # The namespace dex is running in
