{{  if and
  .Values.oidc.clientID.value .Values.oidc.clientID.secret .Values.oidc.clientID.secret.name
  .Values.oidc.clientSecret.value .Values.oidc.clientSecret.secret .Values.oidc.clientSecret.secret.name
  (eq .Values.oidc.clientID.secret.name .Values.oidc.clientSecret.secret.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oidc.clientID.secret.name }}
  namespace: {{ .Release.Namespace  }}
type: Opaque
data:
  {{ required "Missing oidc.clientID.secret.key" .Values.oidc.clientID.secret.key }}: {{ .Values.oidc.clientID.value | b64enc }}
  {{ required "Missing oidc.clientSecret.secret.key" .Values.oidc.clientSecret.secret.key }}: {{ .Values.oidc.clientSecret.value | b64enc }}
{{ else }}

{{  if and .Values.oidc.clientID.value .Values.oidc.clientID.secret .Values.oidc.clientID.secret.name}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oidc.clientID.secret.name }}
  namespace: {{ .Release.Namespace  }}
type: Opaque
data:
  {{ required "Missing oidc.clientID.secret.key" .Values.oidc.clientID.secret.key }}: {{ .Values.oidc.clientID.value | b64enc }}
{{ end }}

{{  if and .Values.oidc.clientSecret.value .Values.oidc.clientSecret.secret .Values.oidc.clientSecret.secret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oidc.clientSecret.secret.name }}
  namespace: {{ .Release.Namespace  }}
type: Opaque
data:
  {{ required "Missing oidc.clientSecret.secret.key" .Values.oidc.clientSecret.secret.key }}: {{ .Values.oidc.clientSecret.value | b64enc }}
{{ end }}

{{ end }}

