---
apiVersion: v1
kind: Service
metadata:
  name: dexgate
  namespace: {{ .Release.Namespace  }}
  labels:
    app: dexgate
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: http
      protocol: TCP
  selector:
    app: dexgate

