# Image URL to use all building/pushing image targets
VERSION ?= v0.1.1
IMG ?= ghcr.io/opendataplatform/dexgate:$(VERSION)


.PHONY: dexgate
dexgate: version
	go build -o bin/dexgate main.go

version:
	@echo "// Generated by Makefile\n\npackage config\n\nvar Version = \"$(VERSION)\"\n" >internal/config/version_.go

# ------------------------------ Docker
# Build the docker image
docker-build: version
	docker build . -t ${IMG}

# Push the docker image
docker-push:
	docker push ${IMG}

docker: docker-build docker-push

doc:
	doctoc README.md --github --title '## Index'