---
logMode: dev
logLevel:   "DEBUG"
bindAddr: ":9999"
targetURL: "http://n0.kspray2:30999"
passthroughs: [ "/favicon.ico" ]
tokenDisplay: False
oidc:
  clientID: dexgate
  clientSecret: Asjhuiu8899ZERtty9K9JST
  issuerURL: https://dex.shared1/dex
  redirectURL: http://bypass.shared1/dg_callback
  #rootCAFile: ca.crt
  scopes:
    - profile
    - groups
    - email
  debug: true
